#! /bin/bash

# Script de limpeza

 export NO_AT_BRIDGE=1 
 
# xcowsay "Browser Clean"

echo RELOADAGENT | gpg-connect-agent

# sleep 3

killall xcowsay xfce4-notifyd

# sleep 2

(ps -x | grep firefox) > /dev/null
if [ $? -eq 0 ]; then
  kill -9 $(ps -x | grep firefox)
else
  killall xcowsay xfce4-notifyd
fi

# sleep 2

ps cax | grep chrome > /dev/null
if [ $? -eq 0 ]; then
  killall xcowsay xfce4-notifyd
  killall chrome &
  pkill gnome-keyring-d
else
  killall xcowsay xfce4-notifyd
fi

# sleep 2

ps cax | grep chromium > /dev/null
if [ $? -eq 0 ]; then
  killall xcowsay xfce4-notifyd
  pkill chromium &
  pkill gnome-keyring-d
else
  killall xcowsay xfce4-notifyd
fi


xcowsay "Iniciando"

# killall firefox &
# killall chrome &
# pkill chromium &

# sleep 2

pkill gnome-keyring-d

killall xcowsay xfce4-notifyd

rm -rf .cache/*
rm -rf ~/.mozilla/
rm -rf ~/.config/google-chrome/
rm -rf ~/.config/chromium/
rm -rf ~/.config/opera-developer/

bleachbit -c chromium.* google_chrome.* flash.* bash.* thumbnails.* system.recent_documents system.tmp system.trash firefox.*

sleep 1

# sweeper --automatic

killall xcowsay xfce4-notifyd

sleep 2

killall xcowsay xfce4-notifyd

unzip .mozilla.zip

sleep 2

echo "Concluido" | xcowsay

exit 
